apiVersion: v2
name: Orion
description: ORganization Identity Operator Notes

type: application

version: 0.1.0-beta2
appVersion: 0.1.0-beta1

dependencies:
  - name: postgresql
    version: 16.5.6
    repository: https://charts.bitnami.com/bitnami
