server:
  image: "bearsan/orion-server"
  database:
    url: "postgres://orion:orion@localhost:5432/orion"
    secret:
      enabled: false
      secretName: ""
      secretKey: ""
  config:
    inline: ""
    exists:
      enabled: false
      kind: ""
      name: ""
      key: ""
console:
  image: "bearsan/orion-console"
  serverUrl: http://localhost:8000
