server:
  image: "bearsan/orion-server"
  database:
    url: "postgres://orion:orion@localhost:5432/orion"
    secret:
      enabled: false
      secretName: ""
      secretKey: ""
console:
  image: "bearsan/orion-console"
  serverUrl: http://localhost:8000
