apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orion-server
      app.kubernetes.io/instance: orion
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orion-server
        app.kubernetes.io/instance: orion
    spec:
      containers:
        - name: orion-server
          image: {{ .Values.server.image }}:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args:
            - --config=/etc/orion/config/provider-config.yaml
          env:
            - name: ORION_DATABASE_URL
              {{ if .Values.server.database.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.database.secret.secretName }}
                  key: {{ .Values.server.database.secret.secretKey }}
              {{ else }}
              value: {{ .Values.server.database.url }}
              {{ end }}
          {{ if .Values.server.config.exists.enabled }}
          volumeMounts:
            - mountPath: /etc/orion/config
              name: config
          {{ end }}
      {{ if .Values.server.config.exists.enabled }}
      volumes:
        - name: config
          {{ if eq .Values.server.config.exists.kind "ConfigMap" }}
          configMap:
            name: {{ .Values.server.config.exists.name }}
            items:
              - key: {{ .Values.server.config.exists.key }}
                path: provider-config.yaml
          {{ else if eq .Values.server.config.exists.kind "Secret" }}
          secret:
            secretName: {{ .Values.server.config.exists.name }}
            items:
              - key: {{ .Values.server.config.exists.key }}
                path: provider-config.yaml
          {{ end }}
      {{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-console
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orion-console
      app.kubernetes.io/instance: orion
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orion-console
        app.kubernetes.io/instance: orion
    spec:
      containers:
        - name: orion-server
          image: {{ .Values.console.image }}:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: API_BASE_URL
              value: {{ .Values.console.serverUrl }}
