apiVersion: v1
kind: Service
metadata:
  name: orion-server
spec:
  selector:
    app.kubernetes.io/name: orion-server
    app.kubernetes.io/instance: orion
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: orion-service
spec:
  selector:
    app.kubernetes.io/name: orion-console
    app.kubernetes.io/instance: orion
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
